name: Entur/Helm/Lint

on:
  workflow_call:
    inputs:
      environment:
        description: "The target environment"
        required: true
        type: string
      chart:
        description: "The chart, defaults to `helm/$repository_name`"
        type: string
        default: "default"
      values:
        description: "The values file in `./helm/$app/env/`, default `values-kub-ent-$environment.yaml`"
        type: string
        default: "default"
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 3

jobs:
  helm-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    name: Helm lint
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: entur/gha-helm/.github/actions/helm-lint@v1
        with:
          environment: ${{ inputs.environment }}
          chart: ${{ inputs.chart }}
          values: ${{ inputs.values }}
